### ISSUE TITLE
replace_with does not work for arguments of a node

### ISSUE THREAD

**Issue by WilcoKruijer** [alvinwan/TexSoup#119]
```python3
soup = TexSoup(r"\somecommand{\anothercommand}")
some_obj = TexNode(TexText("new text"))
soup.somecommand.anothercommand.replace_with(some_obj)
```
Gives

```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wilco/.cache/pypoetry/virtualenvs/viaduct-CDUJVlHg-py3.8/lib/python3.8/site-packages/TexSoup/data.py", line 573, in replace_with
    self.parent.replace(self, *nodes)
  File "/home/wilco/.cache/pypoetry/virtualenvs/viaduct-CDUJVlHg-py3.8/lib/python3.8/site-packages/TexSoup/data.py", line 597, in replace
    self.expr.remove(child.expr),
  File "/home/wilco/.cache/pypoetry/virtualenvs/viaduct-CDUJVlHg-py3.8/lib/python3.8/site-packages/TexSoup/data.py", line 838, in remove
    self._assert_supports_contents()
  File "/home/wilco/.cache/pypoetry/virtualenvs/viaduct-CDUJVlHg-py3.8/lib/python3.8/site-packages/TexSoup/data.py", line 1084, in _assert_supports_contents
    raise TypeError(
TypeError: Command "somecommand" has no children. `add_contents` is only validfor: 1. environments like `itemize` and 2. `\item`. Alternatively, you can add, edit, or delete arguments by modifying `.args`, which behaves like a list.
```
The `replace_with` method tries to replace a child of 'somecommand' but we are dealing with an argument instead. The documentation does not mention this limitation. 

In my use case I am parsing all `newcommand`s, then replacing these commands with their values. I.e.
```latex
\newcommand{\test}{Just a test}
\stuff{\test}
```
Should be converted to
```latex
\newcommand{\test}{Just a test}
\stuff{Just a test}
```
In this case I do not know I am operating on an argument of a node instead of a child of this node. Is there a workaround?

**Comment by peterzjx** [comment]
I had the same need of replacing inside the argument, and I ended up writing a loop to check for all `args.contents` and set the values manually. However please be aware of the subtle usage of setter/getter as described in https://github.com/alvinwan/TexSoup/issues/113
