### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by michaelmior** [alvinwan/TexSoup#35]
The following code fails to parse. I've done my best to try to condense this to a minimal example. Strangely, it works fine if the environment is `align*` instead of `flalign*`.

```latex
\begin{flalign*}
    \bigl[a & b \\
          c & \{{\cal C}\}\bigr] &
\end{flalign*}
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/__init__.py", line 84, in TexSoup
    parsed, src = read(tex)
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/tex.py", line 19, in read
    content = read_tex(buf)
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/reader.py", line 246, in read_tex
    read_env(src, expr)
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/reader.py", line 319, in read_env
    contents.append(read_tex(src))
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/reader.py", line 242, in read_tex
    expr.args.append(read_tex(src))
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/reader.py", line 249, in read_tex
    return read_arg(src, c)
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/reader.py", line 348, in read_arg
    return Arg.parse(content)
  File "/home/mmior/.pyenv/versions/3.6.4/lib/python3.6/site-packages/TexSoup/data.py", line 431, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['[', 'a & b \\\\\n          c & \\{', RArg('\\cal', ' C'), TexCmd(''), '}'].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.
```

**Comment by alvinwan** [comment]
Thanks for reporting! I see the issue--I explicitly list `align` and `align*`as "environments to not render and regurgitate verbatim", via https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L15. I've never heard of `flalign*` until now but am more than happy to add it; do you know if there's a comprehensive list somewhere of related environments? Not sure what this would be called. "Math environment" doesn't do it.

**Comment by michaelmior** [comment]
Good question. [This wiki](http://latex.wikia.com/wiki/List_of_LaTeX_environments) has a reasonable list of environments although you may have to read through them to get what you're looking for.

**Comment by alvinwan** [comment]
@michaelmior Thanks for the link; that was very helpful. Just pushed and master now contains the fix. I'll wait for a few more fixes before I deploy to pypi again. Sorry for the delay.

**Comment by michaelmior** [comment]
No problem on the delay. Thanks so much for fixing!
