### ISSUE TITLE
\tcode{\{}

### ISSUE THREAD

**Issue by h4ck3rm1k3** [alvinwan/TexSoup#40]
This input string that escapes a { char is throwing off the parser

```
\tcode{\{}
```

I suppose It results in turning the } into a RArg to greedly when it should escape the \{ and leave the final } for matching.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/mnt/test/home/mdupont/backup/experiments/cpp/draft/parse.py", line 1, in <module>
    import pprint
  File "/mnt/test/home/mdupont/backup/experiments/cpp/tex2py/tex2py/__init__.py", line 12, in tex2py
    return TreeOfContents.fromLatex(tex, *args, **kwargs)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/tex2py/tex2py/tex2py.py", line 230, in fromLatex
    source = TexSoup(tex)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/__init__.py", line 84, in TexSoup
    parsed, src = read(tex)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/tex.py", line 19, in read
    content = read_tex(buf)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/reader.py", line 251, in read_tex
    expr.args.append(read_tex(src))
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/reader.py", line 258, in read_tex
    return read_arg(src, c)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/reader.py", line 364, in read_arg
    return Arg.parse(content)
  File "/mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/data.py", line 447, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['{', TexCmd('', [RArg()])].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /mnt/test/home/mdupont/backup/experiments/cpp/TexSoup/TexSoup/data.py(447)parse()
-> ' mistyped closing punctuation, misalignment.' % (str(s)))
(Pdb) 
```

**Comment by h4ck3rm1k3** [comment]
I see that on line 238 of reader the 
  	        # TODO: should really be handled by tokenizer
this makes sense because it seems that the tokens are not being read properly

**Comment by alvinwan** [comment]
@h4ck3rm1k3 Thanks for reporting! Darn, it looks like escaped characters are really beginning to bite me in the butt. I'll take a closer look after this week. The `punctuation_command` tokenizer may be wreaking some havoc https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L102

**Comment by h4ck3rm1k3** [comment]
It might be a good time to capture line numbers and columns for tokens as well if you are going to work on a tokenizer. There appears to be a start of a antlr grammar here https://github.com/AkiraHakuta/antlr4_tex2sym/blob/master/tex2sym.g4

**Comment by alvinwan** [comment]
Whoa I hadn't heard of antlr until now, thanks! I've been avoiding math environments... but this looks sweet.

**Comment by SimonMaenaut** [comment]
Seems #41 might fix this issue.
```
simon@zap:~/TexSoup$ python3.6
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from TexSoup import TexSoup
>>> t = TexSoup("\\tcode{\{}")
>>> t.tcode
\tcode{\{}
>>> t.tcode.args
[RArg('\\{')]
>>> t.tcode.args(0)
RArg('\\{')
>>> t.tcode.args[0]
'\\{'
>>> list(t.tcode.contents)
['\\{']
>>> list(t.tcode.contents)[0]
'\\{'
>>> type(list(t.tcode.contents)[0])
<class 'TexSoup.utils.TokenWithPosition'>
>>> exit()
simon@zap:~/TexSoup$ 
```
