### ISSUE TITLE
Cannot parse command after `\item`

### ISSUE THREAD

**Issue by AnatolyShirykalov** [alvinwan/TexSoup#53]
I tried to parse tex-code, that contains 
```
\item\another_command
```

I have got the error ``AttributeError: 'str' object has no attribute 'text'``. Trace:
```
[2018-11-28 19:20:25,248: ERROR/ForkPoolWorker-1] Task edu.tasks.parse_tex_file[3333f77a-f930-4b55-b71f-10207cf678d3] raised unexpected: AttributeError("'str' object has no attribute 'text'")
Traceback (most recent call last):
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/anatoly/projects/edukaka/edu/tasks.py", line 12, in parse_tex_file
    print(TexSoup(f.read()))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/__init__.py", line 84, in TexSoup
    parsed, src = read(tex)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/tex.py", line 19, in read
    content = read_tex(buf)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 246, in read_tex
    read_env(src, expr)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 319, in read_env
    contents.append(read_tex(src))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 246, in read_tex
    read_env(src, expr)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 319, in read_env
    contents.append(read_tex(src))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 246, in read_tex
    read_env(src, expr)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 319, in read_env
    contents.append(read_tex(src))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 229, in read_tex
    extra = read_item(src)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 269, in read_item
    last = stringify(src.forward_until(criterion))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 263, in <lambda>
    stringify = lambda s: TokenWithPosition.join(s.split(' '), glue=' ')
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/utils.py", line 148, in join
    return TokenWithPosition(glue.join(t.text for t in tokens),
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/utils.py", line 148, in <genexpr>
    return TokenWithPosition(glue.join(t.text for t in tokens),
AttributeError: 'str' object has no attribute 'text'
```

The problem can be solved by additional space symbol
```
\item \another_command
```

P.S. It looks like TexSoup also does not parse `\item[marker]`

**Comment by alvinwan** [comment]
Thanks for reporting @AnatolyShirykalov! (In addition to all of the other issues you reported as well). The `0.1.4` bump fixes the first bug.

```
>>> TexSoup(r"""\item\another_command""")
\item \another_command
```

However, it fails for `\item[marker]`, so I will leave this open and investigate the latter.
