### ISSUE TITLE
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment

### ISSUE THREAD

**Issue by AnatolyShirykalov** [alvinwan/TexSoup#54]
The issue is sometimes we obtain
```
[2018-11-28 19:54:28,350: ERROR/ForkPoolWorker-1] Task edu.tasks.parse_tex_file[9d9e412d-c1be-4499-b863-b8fa6fc8193c] raised unexpected: TypeError("Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['[', '\\nsth\\n\\\\]\\n'].\nCommon issues include: Unescaped special characters, mistyped closing punctuation, misalignment.")
Traceback (most recent call last):
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/anatoly/projects/edukaka/edu/tasks.py", line 17, in parse_tex_file
    print(TexSoup(prepare_tex(f.read())))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/__init__.py", line 84, in TexSoup
    parsed, src = read(tex)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/tex.py", line 19, in read
    content = read_tex(buf)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 242, in read_tex
    expr.args.append(read_tex(src))
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 249, in read_tex
    return read_arg(src, c)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/reader.py", line 348, in read_arg
    return Arg.parse(content)
  File "/home/anatoly/projects/edukaka/lenv/lib/python3.7/site-packages/TexSoup/data.py", line 431, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['[', '\nsth\n\\]\n'].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.
```

How to repeate
1. 
```
\[
  sth
\]
\[
  sth
\]
```
2. 
```
\begin{document}
\section{e}
\[
sth
\]

\[
sth
\]
\end{document}
```
3.
```
\[
sth
\]
ss
\[
sth
\]
```

The next examples do not produce this error
1.
```

\[
sth
\]
\[
sth
\]
```
2.
```
\begin{document}
\section{e}
\[
sth
\]
\[
sth
\]
\end{document}
```
3.
```
\begin{document}
\section{e}
\[
sth
\]
s
\[
sth
\]
\end{document}
```

**Comment by alvinwan** [comment]
Thanks for reporting @AnatolyShirykalov ! Just pushed `0.1.4` which fixes this:

```
>>> from TexSoup import TexSoup
>>> TexSoup("""\[
...     \textrm{supp} f = \overline{\{p \in M|f(p) \neq 0\}}
... \]""")
\[
    	extrm{supp} f = \overline{\{p \in M|f(p)
eq 0\}}
\]
>>> TexSoup("""\[
...   sth
... \]
... \[
...   sth
... \]""")
\[
  sth
\]
\[
  sth
\]
>>> TexSoup("""\begin{document}
... \section{e}
... \[
... sth
... \]
...
... \[
... sth
... \]
... \end{document}""")
egin{document}
\section{e}
\[
sth
\]

\[
sth
\]
\end{document}
>>> TexSoup("""\[
... sth
... \]
... ss
... \[
... sth
... \]""")
\[
sth
\]
ss
\[
sth
\]
```
