### ISSUE TITLE
Problem parsing intervals

### ISSUE THREAD

**Issue by deyandyankov** [alvinwan/TexSoup#70]
hi,

I found the following issue:
```
>>> from TexSoup import TexSoup
>>> tex_string = """
... \\documentclass{article}
... \\begin{document}
... [0.0,0.5]
... \\end{document}
... """
>>> TexSoup(tex_string)

\documentclass{article}
\begin{document}[0.0,0.5]
\end{document}

>>> from TexSoup import TexSoup
>>> tex_string = """
... \\documentclass{article}
... \\begin{document}
... [0.0,0.5)
... \\end{document}
... """
>>> TexSoup(tex_string)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\__init__.py", line 85, in TexSoup
    parsed, src = read(tex_code)
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\tex.py", line 19, in read
    content = read_tex(buf)
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\reader.py", line 271, in read_tex
    tex_text = read_tex(src)
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\reader.py", line 282, in read_tex
    return read_arg(src, c)
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\reader.py", line 396, in read_arg
    return Arg.parse(content)
  File "C:\UBS\Dev\miniconda\lib\site-packages\TexSoup\data.py", line 470, in parse
    ' mistyped closing punctuation, misalignment.' % (str(s)))
TypeError: Malformed argument. First and last elements must match a valid argument format. In this case, TexSoup could not find matching punctuation for: ['[', '0.0,0.5)\n', '\\end', RArg('document'), '\n'].
Common issues include: Unescaped special characters, mistyped closing punctuation, misalignment.
>>>
```

Those are both valid and compile-able TeX documents. The difference is in the closing interval bracket, i.e. in the first case it is `]` and in the second case it is `)`. The issue is reproducible on both TexSoup 0.2.0 and 0.1.4.

Seems like this is the same as https://github.com/alvinwan/TexSoup/issues/6
Apologies for not being able to provide a fix.. great package!

**Comment by waschk** [comment]
I stumbled upon the same issue with something like
```
\begin{document}{[}hi{]}\end{document}
```
(prints just `[hi]`)

Only curly brackets have a special meaning in TeX. Others may be used by macros as delimiters, like \newcommand does for optional arguments, but are treated just like any other character by TeX.
```
\def\bracketfun#1[(#2[{#1 #2}
\bracketfun Hello[(World[
```
Is perfectly valid TeX to print "Hello World"
