### ISSUE TITLE
comments after \\

### ISSUE THREAD

**Issue by mennucc** [alvinwan/TexSoup#75]
Dear alvinwan, 
the following fails

 `TexSoup.TexSoup( open('acci.tex').read() )`

where acci.tex is in attachment;

while this loops forever, issuing empty tokens:

```
z = TexSoup.reader.tokenize(open('acci.tex').read())
for tok in z:
    print(repr(tok))
    if str(tok) == '':
        print("empty token!")
sys.exit(0)
```
The file acci.tex  compiles fine with latex

[acci.tex](https://github.com/alvinwan/TexSoup/files/3726224/acci.txt)

Regards

**Comment by alvinwan** [comment]
@mennucc Oh wow, thanks for the clear, concise test case. This is really helpful, will address when I get a chance.

**Comment by AndrewAtLarge** [comment]
This is possibly another instance of the same problem:
```
>>> from TexSoup import TexSoup
>>> TexSoup(r"""\documentclass{article}
... \begin{document}
...  \\%
... \end{document}
... """)
```
Rather than looping this results in the error:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.7/site-packages/TexSoup/__init__.py", line 83, in TexSoup
    parsed, src = read(tex_code)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/tex.py", line 19, in read
    content = read_tex(buf)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 264, in read_tex
    read_env(src, expr)
  File "/usr/local/lib/python3.7/site-packages/TexSoup/reader.py", line 358, in read_env
    raise EOFError('Expecting \\end{%s}. %s' % (expr.name, explanation))
EOFError: Expecting \end{document}. Reached end of file.
```
