### ISSUE TITLE
Does not support Python 3.8

### ISSUE THREAD

**Issue by tanayseven** [alvinwan/TexSoup#86]
Possible to include `tox` for running tests against multiple Python versions?

```
Traceback (most recent call last):
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/config/__init__.py", line 73, in main
    config = _prepareconfig(args, plugins)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/config/__init__.py", line 223, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/config/__init__.py", line 794, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1000, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/config/__init__.py", line 948, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/importlib/metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "/Users/<username>/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/pytest_cov/plugin.py", line 6, in <module>
    from coverage.misc import CoverageException
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/__init__.py", line 10, in <module>
    from coverage.control import coverage, process_startup
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/control.py", line 14, in <module>
    from coverage.html import HtmlReporter
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/html.py", line 8, in <module>
    from coverage.phystokens import source_token_lines, source_encoding
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/phystokens.py", line 5, in <module>
    from coverage.parser import generate_tokens
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/parser.py", line 321, in <module>
    OP_BREAK_LOOP = _opcode('BREAK_LOOP')
  File "/Users/<username>/Library/Caches/pypoetry/virtualenvs/proj_name/lib/python3.8/site-packages/coverage/parser.py", line 280, in _opcode
    return dis.opmap[name]
KeyError: 'BREAK_LOOP'
```

**Comment by alvinwan** [comment]
Oof, thanks for the heads up. Will have to make this a priority when I come back around to TexSoup.

**Comment by alvinwan** [comment]
@tanayseven Thanks again for reporting. It looks like coverage was the culprit. Per https://github.com/okpy/ok-client/pull/384/files, I updated coveralls to 4.4 and this seemed to fix the problem. Waiting for tests to pass #88
